(function(){
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
  let s={screen:null,difficulty:'easy',xp:0,hearts:5,streak:0,correct:0,total:0,game:null,question:null,locked:false,timer:null};
  const levels={
    easy:{label:'EASY',color:'#75e34d',games:[{id:'verb',name:'VERB SPRINT',icon:'V',desc:'Pick the correct Present Simple form.'},{id:'routine',name:'DAILY ROUTINE',icon:'R',desc:'Complete everyday actions correctly.'},{id:'dodoes',name:'DO / DOES',icon:'?',desc:'Choose the correct question helper.'},{id:'frequency',name:'FREQUENCY TAP',icon:'↺',desc:'Choose always, usually, never and more.'}]},
    hard:{label:'HARD',color:'#ffad3d',games:[{id:'order',name:'WORD ORDER',icon:'↔',desc:'Build clean Present Simple sentences.'},{id:'spot',name:'SPOT THE ERROR',icon:'!',desc:'Find the grammar mistake.'},{id:'likes',name:'LIKE / LOVE / HATE',icon:'♥',desc:'Choose the natural preference sentence.'},{id:'routine2',name:'ROUTINE BUILDER',icon:'◫',desc:'Put a daily routine into the right order.'}]},
    difficult:{label:'DIFFICULT',color:'#ff4e66',games:[{id:'mixed',name:'MIXED GRAMMAR',icon:'⚡',desc:'Fast mixed Present Simple decisions.'},{id:'rewrite',name:'FIX THE SENTENCE',icon:'✎',desc:'Rewrite the sentence correctly.'},{id:'challenge',name:'FINAL CHALLENGE',icon:'★',desc:'One mistake can break the streak.'}]}
  };
  const verbQs=[['She ___ to school every day.',['go','goes','going'],'goes'],['They ___ football on Fridays.',['play','plays','playing'],'play'],['He ___ TV at night.',['watch','watches','watching'],'watches'],['I ___ breakfast at 7 a.m.',['have','has','having'],'have'],['My sister ___ music.',['love','loves','loving'],'loves'],['We ___ English at school.',['study','studies','studying'],'study']];
  const routineQs=[['I ___ up at 6 a.m.',['wake','wakes','waking'],'wake'],['She ___ a shower before school.',['take','takes','taking'],'takes'],['He ___ his homework after dinner.',['do','does','doing'],'does'],['They ___ home by bus.',['go','goes','going'],'go'],['My dad ___ coffee in the morning.',['drink','drinks','drinking'],'drinks'],['Anna ___ her uniform every day.',['wear','wears','wearing'],'wears']];
  const doDoes=[['___ you like anime?',['Do','Does','Is'],'Do'],['___ she study Science?',['Do','Does','Are'],'Does'],['___ they play football?',['Do','Does','Is'],'Do'],['___ he watch TV?',['Do','Does','Are'],'Does'],['What ___ she do after school?',['do','does','is'],'does'],['Where ___ they study?',['do','does','is'],'do']];
  const freq=[['He ___ plays football on Sundays.',['always','does','is'],'always'],['I ___ study after dinner.',['usually','does','am'],'usually'],['She ___ watches horror movies.',['never','do','is'],'never'],['They ___ go swimming in summer.',['often','does','are'],'often'],['We ___ eat pizza on Friday.',['sometimes','does','is'],'sometimes']];
  const orderQs=[['Do','you','like','music','?'],['She','usually','plays','tennis','.'],['Does','he','watch','TV','?'],['They','never','eat','fish','.'],['What','do','you','do','after','school','?'],['Does','she','love','comedy','shows','?']];
  const spotQs=[['She go to school every day.',['go','goes','going'],'goes'],['He play football on Saturday.',['play','plays','playing'],'plays'],['They watches TV at night.',['watch','watches','watching'],'watch'],['My sister study English.',['study','studies','studying'],'studies'],['Does she likes anime?',['like','likes','liking'],'like']];
  const likesQs=[['She ___ wearing jeans.',['like','likes','liking'],'likes'],['He ___ horror movies.',['love','loves','loving'],'loves'],['I ___ boring subjects.',['hate','hates','hating'],'hate'],['My brother ___ football.',['likes','like','liking'],'likes'],['We ___ comedy shows.',['love','loves','loving'],'love']];
  const mixedQs=[['She ___ usually late for class.',['is','are','am'],'is'],['___ your brother play football?',['Do','Does','Is'],'Does'],['They ___ English on Mondays.',['study','studies','studying'],'study'],['He never ___ jeans.',['wear','wears','wearing'],'wears'],['What ___ you do after school?',['do','does','is'],'do'],['My sister ___ TV every night.',['watch','watches','watching'],'watches']];
  const rewriteQs=[['She go to school every day.','She goes to school every day.'],['Does he likes anime?','Does he like anime?'],['They plays football on Friday.','They play football on Friday.'],['He watchs TV at night.','He watches TV at night.'],['I usually goes home by bus.','I usually go home by bus.']];
  const challengePool=[...verbQs,...routineQs,...doDoes,...freq,...mixedQs];
  const routineOrder=[['wake up','brush my teeth','have breakfast','go to school'],['get dressed','have breakfast','go to school','study English'],['do homework','have dinner','watch TV','go to bed']];
  const gameFns={verb,routine,dodoes,frequency,order,spot,likes,routine2,mixed,rewrite,delpino:delPino,challenge};
  function open(){s={screen:$('screen'),difficulty:'easy',xp:0,hearts:5,streak:0,correct:0,total:0,game:null,question:null,locked:false,timer:null};PSR_AUDIO?.playModeMusic?.('solo');renderHome()}
  function clear(){if(s.timer){clearInterval(s.timer);clearTimeout(s.timer);s.timer=null}window.onkeydown=null}
  function shell(content){s.screen.innerHTML=`<section class="solo-shell solo-v9"><div class="solo-top"><button class="solo-back" onclick="PSR_SOLO.exit()">← MAIN MENU</button><div class="solo-brand"><b>SOLO QUEST</b><span>PRESENT SIMPLE • 1 PLAYER</span></div><div class="solo-stats"><span>❤ ${s.hearts}</span><span>🔥 ${s.streak}</span><span>⭐ ${s.xp} XP</span></div></div>${content}</section>`}
  function renderHome(){const lv=levels[s.difficulty];shell(`<div class="solo-hero"><div class="solo-kicker">1 PLAYER • PRESENT SIMPLE ARCADE</div><h1>SOLO <span>QUEST</span></h1><p>Short educational microgames focused only on Present Simple: routines, frequency, questions, preferences and word order.</p><div class="difficulty-switch">${Object.entries(levels).map(([k,v])=>`<button class="difficulty-btn ${k===s.difficulty?'active':''}" style="--diff:${v.color}" onclick="PSR_SOLO.setDifficulty('${k}')">${v.label}</button>`).join('')}</div><div class="solo-progress"><span style="width:${Math.min(100,s.xp%100)}%"></span></div><small>${lv.label} • ${s.xp} XP • ${s.correct}/${s.total} CORRECT</small></div><div class="solo-grid solo-grid-v9">${lv.games.map((g,i)=>`<button class="solo-game-card" style="--game:${lv.color}" onclick="PSR_SOLO.play('${g.id}')"><span class="solo-card-icon">${g.icon}</span><span class="solo-card-no">${String(i+1).padStart(2,'0')}</span><strong>${g.name}</strong><em>${g.desc}</em><span class="solo-play">PLAY →</span></button>`).join('')}</div><button class="del-pino-card" onclick="PSR_SOLO.play('delpino')"><span class="del-pino-icon">⚡</span><span><b>DEL PINO CHALLENGE</b><em>SPEED CHECK • Timed Present Simple attack. Separate mode from EASY / HARD / DIFFICULT.</em></span><strong>PLAY →</strong></button><div class="solo-note">Three difficulty levels • Every game trains Present Simple • No maths or unrelated subjects.</div>`)}
  function setDifficulty(k){if(!levels[k])return;clear();s.difficulty=k;s.locked=false;PSR_AUDIO?.playModeMusic?.('solo');renderHome()}
  function play(id){clear();s.game=id;s.locked=false;s.question=null;PSR_AUDIO?.playModeMusic?.(id==='delpino'?'delpino':'solo');if(gameFns[id])gameFns[id]()}
  function common(title,subtitle,body,timer=''){const badge=title==='DEL PINO CHALLENGE'?'SPECIAL MODE':levels[s.difficulty].label;shell(`<div class="solo-game-head"><div><div class="solo-kicker">${esc(title)} • ${badge}</div><h2>${esc(subtitle)}</h2></div><div class="solo-head-right">${timer}<button class="secondary-btn" onclick="PSR_SOLO.home()">GAME MENU</button></div></div><div class="solo-play-area solo-v9-area">${body}</div>`)}
  function feedback(ok){s.total++;if(ok){s.correct++;s.streak++;s.xp+=10+(s.streak*2);PSR_AUDIO?.correct?.()}else{s.hearts=Math.max(0,s.hearts-1);s.streak=0;PSR_AUDIO?.wrong?.()}if(s.hearts<=0)gameOver()}
  function next(fn,msg){if(s.hearts<=0)return;const el=document.createElement('div');el.className='solo-feedback good';el.textContent=msg;document.body.appendChild(el);el.animate([{opacity:0,transform:'translate(-50%,-50%) scale(.7)'},{opacity:1,transform:'translate(-50%,-50%) scale(1)'},{opacity:0,transform:'translate(-50%,-65%) scale(1.05)'}],{duration:700}).finished.finally(()=>el.remove());setTimeout(()=>{s.locked=false;fn()},360)}
  function wrong(){const el=document.querySelector('.solo-v9-area');el?.animate([{transform:'translateX(0)'},{transform:'translateX(-8px)'},{transform:'translateX(8px)'},{transform:'translateX(0)'}],{duration:300})}
  function gameOver(){clear();shell(`<div class="solo-result"><div class="solo-kicker">RUN COMPLETE</div><h2>OUT OF HEARTS</h2><div class="result-big">${s.xp}</div><p>XP earned • ${s.correct} correct answers • best streak ${s.streak}</p><button class="primary-btn" onclick="PSR_SOLO.open()">TRY AGAIN</button><button class="secondary-btn" onclick="PSR_SOLO.exit()">MAIN MENU</button></div>`)}
  function multiple(title,q,label){s.question=q;common(label,title,`<div class="solo-question">${esc(q[0])}</div><div class="solo-choices">${q[1].map(o=>`<button class="solo-choice" onclick='PSR_SOLO.answerMultiple(${JSON.stringify(o)})'>${esc(o)}</button>`).join('')}</div><div class="solo-tip">Correct = XP + streak • Wrong = lose 1 heart.</div>`)}
  function verb(){multiple('VERB SPRINT',verbQs[Math.floor(Math.random()*verbQs.length)],'ENGLISH ARENA')}
  function routine(){multiple('DAILY ROUTINE',routineQs[Math.floor(Math.random()*routineQs.length)],'ROUTINE LAB')}
  function dodoes(){multiple('DO / DOES',doDoes[Math.floor(Math.random()*doDoes.length)],'QUESTION LAB')}
  function frequency(){multiple('FREQUENCY TAP',freq[Math.floor(Math.random()*freq.length)],'FREQUENCY LAB')}
  function likes(){multiple('LIKE / LOVE / HATE',likesQs[Math.floor(Math.random()*likesQs.length)],'PREFERENCE LAB')}
  function mixed(){multiple('MIXED GRAMMAR',mixedQs[Math.floor(Math.random()*mixedQs.length)],'MASTER LAB')}
  function spot(){const q=spotQs[Math.floor(Math.random()*spotQs.length)];s.question=q;common('SPOT THE ERROR','FIX THE VERB','ERROR HUNTER',`<div class="solo-question small">${esc(q[0])}</div><div class="solo-choices">${q[1].map(o=>`<button class="solo-choice" onclick='PSR_SOLO.answerMultiple(${JSON.stringify(o)})'>${esc(o)}</button>`).join('')}</div><div class="solo-tip">Pick the form that repairs the sentence.</div>`)}
  function answerMultiple(v){if(s.locked||!s.question)return;s.locked=true;const ok=v===s.question[2];feedback(ok);if(ok)next(()=>play(s.game),'CORRECT!');else{wrong();setTimeout(()=>{if(s.hearts>0){s.locked=false;play(s.game)}},520)}}
  function order(){const target=shuffle(orderQs[Math.floor(Math.random()*orderQs.length)]);s.question={target,chosen:[]};common('WORD ORDER','BUILD THE SENTENCE','LANGUAGE LAB',`<div class="solo-slots" id="soloSlots"><span>Tap words in order.</span></div><div class="solo-word-bank">${shuffle(target).map(w=>`<button class="solo-word" data-w="${esc(w)}" onclick="PSR_SOLO.pickOrder(this)">${esc(w)}</button>`).join('')}</div><button class="primary-btn" onclick="PSR_SOLO.submitOrder()">CHECK ✓</button>`)}
  function pickOrder(el){if(s.locked)return;s.question.chosen.push(el.dataset.w);el.disabled=true;$('soloSlots').innerHTML=s.question.chosen.map(w=>`<span>${esc(w)}</span>`).join(' ')||'<span>Tap words in order.</span>'}
  function submitOrder(){if(s.locked)return;s.locked=true;const ok=normalize(s.question.chosen.join(' '))===normalize(s.question.target.join(' '));feedback(ok);if(ok)next(()=>play('order'),'PERFECT ORDER');else{wrong();setTimeout(()=>{if(s.hearts>0){s.locked=false;order()}},600)}}
  function normalize(v){return String(v).toLowerCase().replace(/\s+([?.!,])/g,'$1').replace(/\s+/g,' ').trim()}
  function routine2(){const seq=shuffle(routineOrder[Math.floor(Math.random()*routineOrder.length)]);s.question={seq,chosen:[]};common('ROUTINE BUILDER','PUT IT IN ORDER','DAILY LIFE',`<div class="solo-slots" id="soloSlots"><span>Tap from first action to last.</span></div><div class="solo-word-bank">${shuffle(seq).map(w=>`<button class="solo-word" data-w="${esc(w)}" onclick="PSR_SOLO.pickRoutine(this)">${esc(w)}</button>`).join('')}</div><button class="primary-btn" onclick="PSR_SOLO.submitRoutine()">CHECK ✓</button>`)}
  function pickRoutine(el){if(s.locked)return;s.question.chosen.push(el.dataset.w);el.disabled=true;$('soloSlots').innerHTML=s.question.chosen.map(x=>`<span>${esc(x)}</span>`).join(' ')||'<span>Tap from first action to last.</span>'}
  function submitRoutine(){if(s.locked)return;s.locked=true;const ok=s.question.chosen.join('|')===s.question.seq.join('|');feedback(ok);if(ok)next(()=>play('routine2'),'ROUTINE COMPLETE');else{wrong();setTimeout(()=>{if(s.hearts>0){s.locked=false;routine2()}},620)}}
  function rewrite(){const q=rewriteQs[Math.floor(Math.random()*rewriteQs.length)];s.question=q;common('FIX THE SENTENCE','REWRITE IT','EDITOR LAB',`<div class="bad-sentence">${esc(q[0])}</div><input id="soloText" class="answer-input solo-text-input" autocomplete="off" placeholder="Type the correct sentence"><button class="primary-btn" onclick="PSR_SOLO.submitRewrite()">CHECK ✓</button><div class="solo-tip">Type the entire corrected Present Simple sentence.</div>`);setTimeout(()=>$('soloText')?.focus(),60)}
  function submitRewrite(){if(s.locked)return;s.locked=true;const v=$('soloText')?.value||'';const ok=normalize(v)===normalize(s.question[1]);feedback(ok);if(ok)next(()=>play('rewrite'),'FIXED PERFECTLY');else{wrong();setTimeout(()=>{if(s.hearts>0){s.locked=false;rewrite()}},700)}}
  function delPino(){const q=challengePool[Math.floor(Math.random()*challengePool.length)];s.question=q;let t=5.5;common('DEL PINO CHALLENGE','SPEED CHECK','TIME ATTACK',`<div class="speed-clock" id="speedClock">5.5</div><div class="solo-question small">${esc(q[0])}</div><div class="solo-choices">${q[1].map(o=>`<button class="solo-choice" onclick='PSR_SOLO.answerDelPino(${JSON.stringify(o)})'>${esc(o)}</button>`).join('')}</div>`);s.timer=setInterval(()=>{t-=.1;const c=$("speedClock");if(c)c.textContent=Math.max(0,t).toFixed(1);if(t<=0){clear();if(s.locked)return;s.locked=true;feedback(false);wrong();setTimeout(()=>{if(s.hearts>0){s.locked=false;delPino()}},450)}},100)}
  function answerDelPino(v){if(s.locked)return;s.locked=true;clear();const ok=v===s.question[2];feedback(ok);if(ok)next(()=>play('delpino'),'DEL PINO HIT');else{wrong();setTimeout(()=>{if(s.hearts>0){s.locked=false;delPino()}},500)}}
  function challenge(){const q=challengePool[Math.floor(Math.random()*challengePool.length)];s.question=q;common('FINAL CHALLENGE','ONE LIFE. ONE ANSWER.','PRESENT SIMPLE BOSS',`<div class="boss-bar"><span style="width:${Math.min(100,s.streak*10)}%"></span></div><div class="solo-question small">${esc(q[0])}</div><div class="solo-choices">${q[1].map(o=>`<button class="solo-choice" onclick='PSR_SOLO.answerChallenge(${JSON.stringify(o)})'>${esc(o)}</button>`).join('')}</div><div class="solo-tip">In DIFFICULT, one wrong answer breaks the current streak.</div>`)}
  function answerChallenge(v){if(s.locked)return;s.locked=true;const ok=v===s.question[2];feedback(ok);if(ok)next(()=>play('challenge'),'BOSS HIT');else{wrong();setTimeout(()=>{if(s.hearts>0){s.locked=false;challenge()}},700)}}
  function exit(){clear();PSR_AUDIO?.stopMusic?.();if(window.PSR_GAME)PSR_GAME.backHome()}
  window.PSR_SOLO={open,home:renderHome,play,setDifficulty,answerMultiple,pickOrder,submitOrder,pickRoutine,submitRoutine,submitRewrite,answerDelPino,answerChallenge,exit};
})();